version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prd-predict-demand"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-twa0spcxc0zk"
s3_prefix = "prd-predict-demand"
region = "us-east-1"
profile = "Law"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
parameter_overrides = "Stage=\"prd\" EndpointUrl=\"None\" Region=\"us-east-1\" S3Name=\"aws-sam-cli-gr/model\" ModelS3Name=\"demand.sav\""
