AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "SAM Template for Retailers Manager"

Parameters:
  RetailerInfoTableName:
    Type: String

  EndpointUrl:
    Type: String
    Default: None

  Region:
    Type: String
    Default: us-east-1

Globals:
  Function:
    Timeout: 900
    MemorySize: 128
    Runtime: python3.8

Resources:
  RetailerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "retailer-api"

  RetailerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "retailer-manager"
      CodeUri: lambda/
      Handler: src.app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RetailerInfoTableName
      Environment:
        Variables:
          TABLE_NAME: !Ref RetailerInfoTableName
          ENDPOINT_URL: !Ref EndpointUrl
          REGION: !Ref Region
      Events:
        CancelDlJobRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RetailerApi
            Path: /add
            Method: POST

Outputs:
  RetailerFunction:
    Description: "Retailer Info Lambda Function ARN"
    Value: !GetAtt RetailerFunction.Arn